### ISSUE TITLE
Populate README

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/unstructured-grid-viz-cookbook#1]

**Comment by erogluorhan** [comment]
On it right now

**Comment by philipc2** [comment]
> On it right now

Thanks! It should be mostly complete, we will need to update some of the links once we migrate the ownership to Pythia.

**Comment by erogluorhan** [comment]
I believe I've finished it, adding a motivation part, adding more into the structure part, updating the running on your own machine part. Yes the link in the very beginning should be updated after transferring the ownership.
